Fix incorrect method injection types, prettier for TypeScript, incorrect stuff in the script itself
TheRolfFR/firestorm-db pull request #15
Opened 2023-11-03 04:20 UTC by 3vorp

Should close #14 and also generally clean things up. This does not close #13 since I can't figure out how to do a recursive `keyof` that keeps the property hierarchy — it may be necessary to just use a string type if all else fails.

2023-11-05 18:31 UTC, Juknum commented
For the recursive keys you can take a look at [what nestjs-i18n](https://github.com/toonvanstrijp/nestjs-i18n/blob/3fc33c105a68b112ed7af6237c5f49902d0864b6/src/types.ts#L27) have done:

<img width="572" alt="Capture d’écran 2023-11-05 à 19 28 32" src="https://github.com/TheRolfFR/firestorm-db/assets/49886317/84d7bcf7-c3f0-496a-9d83-72991fbba957">

2023-12-16 05:35 UTC, 3vorp commented
All tests are passing and I've gotten the Faithful API to entirely work with my proposed type changes.

2023-12-17 10:01 UTC, TheRolfFR requested changes

2023-12-17 12:08 UTC, 3vorp commented on src/index.js
> +	}
yeah I've seen a bunch of other libraries do similar to minimize breaking changes, in vscode this actually comes up marked with strikethrough too

2023-12-17 12:12 UTC, TheRolfFR approved these changes

2023-12-17 12:23 UTC, merged