PHP 8 + Container image goal
TheRolfFR/firestorm-db pull request #16
Opened 2023-11-21 18:30 UTC by TheRolfFR

## Container integration and pack

I thought Docker and docker integration could be an easy way to update and maintain the project as it creates an image that could be updated regularly on Docker Hub.

To do so, I created a Dockerfile copying required files into the specified apache directory, in the default route.

Some items are still missing though:
- [ ] Add GitHub Actions automated tests to test image build, tests on the images and if successful, publication of the image onto Docker Hub + GH release for image (try to use buildah to build OCI image?)
- [ ] Add support for PHP 8 and resolve bugs not working and change Dockerfile to use the latest PHP version
- [ ] Modify tests to matrix PHP 7 and PHP 8 but only test Dockerfile for PHP 7
- [ ] Add environment variable to be able to modify the HTTP port and expose it

2025-03-06 03:03 UTC, 3vorp commented on php/files.php
>          header("Content-type: {$imgInfo['mime']}");
Shouldn't this be Content-Type?

2025-03-06 17:46 UTC, Juknum commented on php/files.php
>          header("Content-type: {$imgInfo['mime']}");
I honestly don't know enough PHP to be 100% sure, but here is the error I had when running it with PHP 8:

```html
<br />
<b>Warning</b>:  Trying to access array offset on value of type bool in <b>/var/www/html/files.php</b> on line <b>119</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /var/www/html/files.php:119) in <b>/var/www/html/files.php</b> on line <b>119</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /var/www/html/files.php:119) in <b>/var/www/html/files.php</b> on line <b>120</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /var/www/html/files.php:119) in <b>/var/www/html/files.php</b> on line <b>121</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /var/www/html/files.php:119) in <b>/var/www/html/files.php</b> on line <b>122</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /var/www/html/files.php:119) in <b>/var/www/html/files.php</b> on line <b>123</b><br />
```

And according to ChatGPT (not the best source I agree):

> The issue arises from trying to access an array offset on a `bool` value, likely because `getimagesize($absolutePath)` is returning `false` (indicating the file might not be a valid image or does not exist). This causes `$imgInfo['mime']` to throw a warning.

2025-03-06 19:28 UTC, Juknum commented
> Could you make us of ARG to build images with multiple php versions and ENV to customize exposed port ([guide](https://vsupalov.com/docker-arg-env-variable-guide/)) ?

Do you want to publish an image for each php version?

> Also could it be possible to matrix the tests of the frontend on multiple Node version? 18 is getting old... 20, 22 and 23 could be more reasonable.

👍 

> Complete tests coverage for PR would be with/without Docker, with PHP7 or PHP8, with Node 20, 22 and 23

I think the best we can have is this:

- With docker & PHP 8 & Node 20
- With docker & PHP 7 & Node 20
- Without docker & PHP 8 & Node [20;22;23]
- Without docker & PHP 7 & Node [20;22;23]

> You may be able to test them locally with [act](https://github.com/nektos/act)

Can't get it to work on my pc :(

2025-03-06 21:55 UTC, TheRolfFR commented on php/files.php
>          header("Content-type: {$imgInfo['mime']}");
Are you sure you did not send content before this header() ?

2025-03-07 00:28 UTC, 3vorp reviewed
Not super familiar with the docker stuff so I didn't comment on that, just suggested a couple of minor php/js improvements

2025-03-07 00:28 UTC, 3vorp commented on php/classes/JSONDatabase.php
> +            throw new HTTPException("Mismatch in keys and values array sizes or invalid input.");
I'd use two error messages, one for mismatched sizes and one for invalid input

2025-03-07 00:28 UTC, 3vorp commented on tests/tests.spec.cjs
> +const PORT = process.env.PORT ? process.env.PORT : '8000'
```suggestion
const PORT = process.env.PORT || "8000"
```
also make sure to run prettier on this before merging the pr

2025-03-07 00:28 UTC, 3vorp commented on tests/tests.spec.cjs
> +const HOUSE_DATABASE_FILE = path.join(__dirname, "files", `${HOUSE_DATABASE_NAME}.json`);
`process.cwd()` has better support than __dirname, especially when calling from ESM contexts

2025-03-07 13:46 UTC, Juknum commented on php/files.php
>          header("Content-type: {$imgInfo['mime']}");
The error was thrown when running tests

2025-03-08 17:43 UTC, TheRolfFR commented on php/files.php
>          header("Content-type: {$imgInfo['mime']}");
This does not answer my question

2025-03-08 17:44 UTC, TheRolfFR commented
Anything to add @3vorp?

2025-03-08 21:33 UTC, 3vorp requested changes
again mostly small stuff

2025-03-08 21:33 UTC, 3vorp commented on php/classes/JSONDatabase.php
> +            throw new HTTPException("Mismatch in keys and values array sizes.");
maybe "Key and value array sizes are not equal"

2025-03-08 21:33 UTC, 3vorp commented on php/classes/JSONDatabase.php
> +                throw new HTTPException("Undefined key at index $i in keys array.");
"Keys array" sounds a bit weird, "key array" is a bit nicer (same with values array, applies everywhere)

2025-03-08 21:33 UTC, 3vorp commented on php/files.php
> +    $errorCode = isset($_FILES['file']['error']) ? $_FILES['file']['error'] : UPLOAD_ERR_OK;
```suggestion
    $errorCode = $_FILES['file']['error'] ?? UPLOAD_ERR_OK;
```
https://www.php.net/manual/en/migration70.new-features.php
supports both php 7 and 8 so it's good on that front

2025-03-08 21:33 UTC, 3vorp commented on php/files.php
> +        http_error(500, isset($errorMessages[$errorCode]) ? $errorMessages[$errorCode] : "Unknown error.");
```suggestion
        http_error(500, $errorMessages[$errorCode] ?? "Unknown error.");
```
same thing as above

2025-03-08 21:33 UTC, 3vorp commented on php/files.php
>          header("Content-type: {$imgInfo['mime']}");
none of this actually answers the question of whether Content-type gets recased by php to Content-Type; I'm pretty sure this is invalid either way

2025-03-08 21:33 UTC, 3vorp commented on src/index.js
> +	 * @param {string|number} key - The key of the element you want to edit
```suggestion
	 * @param {string | number} key - The key of the element you want to edit
```
small formatting tweak

2025-03-08 21:33 UTC, 3vorp commented on tests/php_setup.mjs
> +	consola.error("This script is built for Unix systems only, if you are on Windows, use WSL");
```suggestion
	consola.error("This script is built for Unix systems only. If you are on Windows, use WSL.");
```
https://en.wikipedia.org/wiki/Comma_splice

2025-03-08 21:33 UTC, 3vorp commented on tests/php_setup.mjs
> +async function setup_php() {
should use camelCase, setupPhp or setupPHP would be better (or phpSetup if you don't want php to be weirdly capitalized)

2025-03-08 21:33 UTC, 3vorp commented on tests/tests-setup.spec.mjs
> +	it("binds usable address", function () {
use arrow functions instead of function expressions, goes for the other one here too

2025-03-08 21:33 UTC, 3vorp commented on tests/tests.spec.cjs
> +const PORT = process.env.PORT || "8000";
I don't like how these three lines are repeated in basically all the test files, might be worth creating a `tests-setup-environment` file or something so that if you want to test out changing the token you don't have to look around modifying a bunch of files

2025-03-09 09:06 UTC, 3vorp commented
Oh also I forgot to mention this but make sure to update and bump the changelog when making these changes

2025-03-09 21:18 UTC, Juknum commented on tests/tests-setup.spec.mjs
> +	it("binds usable address", function () {
This was already like that before

2025-03-09 21:24 UTC, Juknum commented on src/index.js
> +	 * @param {string|number} key - The key of the element you want to edit
That's not really relevant

2025-03-09 21:25 UTC, Juknum commented on tests/php_setup.mjs
> +	consola.error("This script is built for Unix systems only, if you are on Windows, use WSL");
Thanks for the advice :)

2025-03-10 02:30 UTC, 3vorp approved these changes
looks pretty good to me

2025-03-10 02:33 UTC, 3vorp commented on tests/tests-setup.spec.mjs
> +	it("binds usable address", function () {
doesn't mean you can't fix it

2025-03-10 02:36 UTC, 3vorp commented on src/index.js
>  	random(max, seed, offset) {
same thing, make sure to update the typescript types to match

2025-03-12 15:07 UTC, 3vorp commented
This is something I just noticed but is really bothering me now: in all the documentation, [SHA-1](https://en.wikipedia.org/wiki/SHA-1) is improperly spelled as sha1.
https://github.com/TheRolfFR/firestorm-db/blob/285eb196f78b388eba8499606cf21338956d65fe/README.md?plain=1#L79
https://github.com/TheRolfFR/firestorm-db/blob/285eb196f78b388eba8499606cf21338956d65fe/src/index.js#L208-L210
https://github.com/TheRolfFR/firestorm-db/blob/285eb196f78b388eba8499606cf21338956d65fe/typings/index.d.ts#L198-L200
This is everywhere the incorrect terminology is used, any chance it can be fixed here? I don't want to open a new PR for something this trivial

2025-04-29 05:39 UTC, 3vorp commented
Any updates on this? It's been nearly two months

2025-05-08 10:59 UTC, TheRolfFR commented
I guess I was waiting for a full review and approval from @Juknum

2025-05-08 11:26 UTC, Juknum commented on php/files.php
>          header("Content-type: {$imgInfo['mime']}");
@3vorp any update?

2025-05-08 11:29 UTC, merged